---
layout: post
title: java31
sitemap: false
hide_last_modified: true
---
# 예외처리

* toc
{:toc .large-only}

# 예외처리
자바에서 처리하는 모든 예외는 `Throwable` 하위의 `Exception` 클래스에 종속된다. `Throwable` 하위에는 `Error` 클래스도 있는데, 이는 JVM의 내부 오류나 리소스 부족 등 시스템 레벨 문제이기 때문에 개발자가 직접 처리하거나 복구하기 어렵다.

- 예: `OutOfMemoryError`,`StackOverflowError`

## 예외 처리 순서

1. 예외 발생
프로그램 실행 중 문제가 생기면 JVM은 해당 예외 객체를 생성하고 `throw`한다. 이는 명시적으로 예외를 발생시키는 `throw`와 다르게 코드에서 문제 발생 시 JVM이 자동으로 던지는 예외이다.

2. 예외 처리기 탐색
예외가 발생한 메서드 내부에서 `try-catch` 블록이 있는지 탐색하고, 없으면 상위 메서드로 올라가며 탐색을 계속한다(예외 전달). 이 때 `checkedException`과 `uncheckedException`의 탐색 방식에 차이가 있다.
- checkedException: `throws`가 명시 되어야만 예외가 상위 메서드로 전달되어 `try-catch`를 탐색한다.
- uncheckedException: JVM이 자동으로 던져주므로 `throws`없이도 호출한 메서드를 타고 올라갈 수 있다.(명시해도 문제없음)

최상위 메서드에도 예외가 처리되지 않으면 JVM이 프로그램을 종료시키고 예외 메시지와 스택 트레이스를 출력한다.


# Exception

![](/assets/img/java/exception.png)

## Checked Exception

컴파일 시 체크하는 예외이다. 컴파일러가 개발자가 해당 예외를 반드시 처리하도록 강제한다.

`RuntimeException` 을 상속 받지 않는 Exception은 모두 `checked Exception` 이다.

대표적으로 `IOException`, `SQLException`, `ClassNotFoundException`등이 있으며, 파일 입출력, 네트워크 퉁신 등 **외부 환경**과의 상호작용 시 발생할 가능성이 높은 예외들로 구성되어있다.

`CheckedException`은 컴파일러가 예외 처리를 강제하기 때문에, 해당 메서드 내에서 예외를 처리 하거나(try-catch), 상위 메서드(호출한 메서드)로 예외를 위임(throws)해야 한다. 이 처리가 되지 않을 시 컴파일 오류가 발생된다. throws로 예외를 던진 후 최상위 메서드까지 처리가 안되면 JVM에서 이를 처리한다(비정상 종료)

## Unchecked Exception

런타임 시 체크 되는 예외로써, 논리적 오류에 의해 발생하는 경우가 많다.

대표적으로 `NullPointerException`, `ArrayIndexOutOfBoundsException`, `ArithmeticException`가 있으며, 모든 Unchecked Exception은 `RuntimeException` 을 상속 받는다.

`RuntimeException`은  try-catch나 throws를 이용한 예외 처리가 강제 되지 않는다. 즉, 예외 처리를 해주지 않아도 프로그램 실행 시 컴파일 오류가 발생하지 않는다.

발생한 예외는 처리 될 때까지 상위 메서드로 전파되며, 최상위까지 처리되지 않은 `Exception` 은 프로그램을 종료 시킨다. 따라서 개발자가 로직상 막을 수 있는 실수는 적절히 처리 해 주는 것이 좋다.


## 비교

|  | checked Exception | unchecked Exception |
| --- | --- | --- |
| 발생 시점 | 컴파일 시 | 런타임 시 |
| 발생 원인 | 외부 환경에서 발생할 수 있는 예측 가능한 문제 | 프로그래밍 오류나 논리적 실수 |
| 처리 | throws나 try-catch로 반드시 처리해주어야 하며, 실행하지 않을 시 컴파일 에러 발생 | 처리가 없어도 실행은 됨 |

`RuntimeException` 는 try-catch나 throws의 여부와 상관 없이 우선 프로그램이 실행되고, `CheckedException` 은 try-catch나 throws가 있어야만 프로그램이 실행된다.

# 처리

## throw

예외를 그 즉시 발생시킨다.

```java
public void register(String id, String pw, String email){
    if(passwordChecker.checkPasswordWeak(pw)) {
        throw new WeakPasswordException();
    }
    // 생략
}
```

## throws

해당 메서드에서 예외 발생 시, 이를 해당 메서드를 호출한 상위 호출자에게 전달한다.

예외 처리를 위임함으로써, 호출한 쪽에서 다양한 방식으로 처리할 수 있게 해준다. 예를 들어, 어떤 곳에서는 에러 로그만 남기고 무시할 수도 있고, 어떤 곳에서는 사용자에게 에러 메시지를 보여주거나, 아예 시스템을 중단시키는 등 다양한 방식으로 처리 할 수 있다.

```java
public void readFile() throws IOException {
    FileReader file = new FileReader("test.txt");  // 파일이 없을 경우 FileNotFoundException 발생
    BufferedReader fileInput = new BufferedReader(file);
    System.out.println(fileInput.readLine());  // 읽는 중에 문제가 발생하면 IOException 발생
}
```

```java
public void process() {
    try {
        readFile();  // readFile()에서 IOException 발생 가능
    } catch (IOException e) {
        System.out.println("Error occurred: " + e.getMessage());  // 예외 처리
    }
}
```

```java
public static void main(String[] args) {
    new Main().process();
}
```

## try-catch

예외가 발생할 수 있는 코드를 `try` 안에 작성하고, `catch` 에서 이를 처리한다. 

```java
public void readFile() throws IOException {
    throw new IOException("파일 없음");  // 예외 터뜨림
}

public void process() {
    try {
        readFile();
    } catch (IOException e) {
        System.out.println("예외 처리 로직 실행!");  // 여기서 처리
    }
}
```

### finally

try-catch와 함께 쓰이며, 예외가 발생 하든 안 하든 항상 실행된다.

```java
		try {
			startInstall();
			copyFiles();
//			deleteFiles();   //코드 중복
		} catch(Exception e ) {
			e.printStackTrace();
//			deleteFiles();//코드 중복
		} finally {
			deleteFiles(); 
		}
```

# Custom Exception

**사용자 정의 예외**는 사용자가 예외의 이름, 메시지를 직접 정의함으로써 원인을 더 명확히 표현하고 상황별로 다르게 처리 할 수 있도록 해준다.

- Custom Exception 없이 처리

```java
try {
    validateInput();
} catch (IllegalArgumentException e) {
    if (e.getMessage().equals("비밀번호가 너무 짧습니다")) {
        // 비밀번호 관련 처리
    } else if (e.getMessage().equals("이메일 형식이 잘못되었습니다")) {
        // 이메일 관련 처리
    } else {
        // 기타 처리
    }
}
```

예외가 발생한 이유는 다르지만 타입이 모두 `IllegalArgumentException`로 같으므로 프론트에서 처리 시 메시지(`비밀번호가 너무 짧습니다`)로 분기 처리를 해야한다. 예외가 많아질수록 어떤 에러인지 구분하기 어렵고, 메시지가 바뀔 시 처리 로직도 깨질 가능성이 있다.

- Custom Exception으로 처리

```java
try {
    validateInput();
} catch (WeakPasswordException e) {
    // 비밀번호 처리
} catch (InvalidEmailException e) {
    // 이메일 처리
}
```

예외 `타입`으로 바로 분기가 가능하며 메시지를 바꿔도 처리 로직이 바뀌지 않는다. 예외마다 상태코드나 로깅도 다르게 설정 할 수 있어서 훨씬 편리하다.

## 참고

[Custom Error Code](https://xxyoonxx.github.io/spring/2025-03-31-spring17/)